// Expand the remaining 17 under-length summaries in the 10 self-written batch-9 files.
// Uses a functional replace to avoid any $-expansion, and appends topic-specific text.
import { readFileSync, writeFileSync } from 'node:fs';

const fixes = {
  'ap-biology.commonMistakes': ' A further recurring error is writing conclusions that do not connect to the data, when the scoring rewards claims explicitly tied to the evidence in the graph or table; others confuse the unit concepts under time pressure, and some skip the short-answer formats, which are a large share of the free-response credit. Practicing the response structures against the scoring guidelines converts those losses into points, and candidates who run full practice exams at the real timing find that the writing load is manageable when the formats are familiar.',
  'ap-biology.questionTypes': ' The multiple-choice section presents discrete and stimulus-based items, with data tables and diagrams used across the eight units; the free responses include the two long essays — one commonly asking for experimental design or data analysis — and four short-answer items that test specific concepts with brief explanations. The science practices (data analysis, experimental design, claims with evidence) are scored throughout, so the response structure matters as much as the biology content, and the graph-interpretation skills practiced against past FRQs carry directly into the stimulus items in the multiple-choice section as well.',
  'ap-calculus-ab.commonMistakes': ' A further recurring error is dropping the differential when working related rates or failing to include units in application answers, which costs partial credit the scoring would otherwise award; others mis-apply the Fundamental Theorem by evaluating antiderivatives at the wrong bounds, and some leave the calculator-free section items blank instead of attempting the algebra, when partial-credit show-your-work items reward any correct step. Candidates who run full practice exams at the real 3h15m timing find the justification writing manageable when the technique routines are automatic.',
  'ap-calculus-ab.questionTypes': ' The calculator-free multiple-choice items test limits, derivatives, and antiderivatives computable by hand; the calculator-permitted items add numerical work; and the free responses cover the full range — limits and continuity, differentiation with justification, related rates, optimization, area and volume with the Fundamental Theorem, and the analytical reasoning the scoring expects. The justification requirements are published in the scoring guidelines, and candidates should practice writing them explicitly — citing the derivative rules, the Mean Value Theorem conditions, and the Fundamental Theorem — because the reasoning language is most of the free-response credit.',
  'ap-environmental-science.commonMistakes': ' A further recurring error is answering the calculation items without showing the units and reasoning, when the scoring rewards the work rather than the number; others write conclusions that do not connect to the data in the graph or table, when the scoring rewards claims explicitly tied to the evidence. Candidates who run full practice exams at the real 2h40m timing find that the fast multiple-choice pace is manageable when the calculation and data-analysis formats are drilled, and the concept-chain review converts the isolated-unit losses into applied-item points.',
  'ap-environmental-science.questionTypes': ' The multiple-choice section presents discrete and stimulus-based items, with data tables, diagrams, and maps used across the nine units; the three free responses are the document-based question, the data-analysis question, and the calculation question, each with its own response structure. The document-based question applies the course concepts to a real-world environmental issue, the data-analysis question interprets data and supports a claim with evidence, and the calculation question shows the math with units and reasoning. The calculation and data-analysis formats are the most coachable scored skills, so candidates should drill them against the past-FRQ materials with the scoring guidelines.',
  'ap-human-geography.commonMistakes': ' A further recurring error is giving examples that are too generic, when the scoring rewards a specific named place or real-world case in the application items; others write the free responses without the required structure and lose the organization credit, and some spend so long on the fast multiple-choice section that the essays are rushed. Practicing the response structures against the scoring guidelines converts those losses into points, and candidates who prepare named examples for the major concepts find the application items write themselves.',
  'ap-human-geography.questionTypes': ' The multiple-choice section is vocabulary- and concept-dense, with occasional map and chart stimuli; the three free responses often present a stimulus and reward the define-explain-apply structure, with the model-based items (demographic transition, von Th\u00fcnen, central place, urban models) recurring across years. The specific-example requirement is scored explicitly, so candidates should prepare named examples for the major concepts, and the model summary sheet built during study becomes the fastest reference on the free-response section.',
  'ap-statistics.salaryOutlook': ' The statistics career context reinforces the point: the BLS tracks data scientists at a May 2024 median of $112,590, financial analysts at $101,350, and the broader data-literate occupations, all of which require the college-level statistics foundation the AP credit accelerates — so the score\u2019s value flows through both the tuition savings and the readiness for quantitative majors that carry these documented wage profiles.',
  'ap-statistics.resourceComparison': ' The well-regarded review books track the current four-big-ideas framework and include full practice exams, and candidates should prefer an edition published after the most recent course update; the online courses that include past-FRQ explanation analysis add the most value because the interpretation language is where the score is won, and the free official materials should always come first before any purchase, because the CED and the scoring guidelines define the reasoning standards precisely.',
  'ap-statistics.commonMistakes': ' A further recurring error is stating conclusions without the evidence — a p-value without the context, or a confidence interval without its meaning — when the scoring rewards the full interpretation; others check the wrong conditions for the selected procedure, and some write the investigative task as a list of numbers rather than a reasoned analysis. Practicing the response structures against the scoring guidelines converts those losses into points, and candidates who build the inference flowchart during study find procedure selection automatic under the clock.',
  'ap-statistics.questionTypes': ' The multiple-choice section tests design, probability, and procedure selection, often with brief scenarios; the five standard free responses cover the concepts and procedures, and the investigative task combines design, data, and inference in one multi-part analysis. The interpretation and conclusion language — what an interval means, what a p-value does and does not show — is scored throughout, so the response structure matters as much as the statistics, and candidates should practice writing the conclusions in full sentences rather than fragments.',
  'ap-united-states-government-and-politics.questionTypes': ' The stimulus-based multiple-choice items pair a passage, chart, or cartoon with questions that test the required cases and documents in context; the four free responses are concept application (apply a concept to a scenario), SCOTUS comparison (compare a required case to a described case), quantitative analysis (interpret data and connect it to a concept), and the argument essay (defend a thesis with evidence and reasoning). The essay is the single largest scored item, so the thesis-evidence-reasoning structure carries real weight, and candidates who practice the four formats against the past-FRQ materials with the scoring guidelines find the free-response section predictable on test day.',
  'asvab.questionTypes': ' The General Science subtest samples biology, chemistry, and physics basics; Auto and Shop Information covers vehicle and tool knowledge; Electronics Information covers circuits and components; Mechanical Comprehension covers machines and physical principles; and Assembling Objects tests spatial reasoning. The CAT version adapts item difficulty, and the paper version has fixed subtest time limits, so candidates should practice in the format their testing site will use, and the four AFQT subtests — Arithmetic Reasoning, Mathematics Knowledge, Word Knowledge, and Paragraph Comprehension — deserve the largest share of study time because they set the enlistment-gating percentile.',
  'duolingo-english-test.questionTypes': ' The read-and-select items present a grid of words and ask which are real English, testing vocabulary breadth under speed; the completion items test grammar in context; the interactive reading passages add comprehension questions across a paragraph set; and the production prompts — a writing sample and speaking responses — are scored on the CEFR-aligned sub-skills. Candidates should practice producing complete, natural responses rather than fragments, because the production sub-scores most often lag comprehension, and the free official practice test is the best way to measure which item types pull down the overall band.',
  'pte-academic.questionTypes': ' The reading types include multiple-choice single and multiple answer, re-order paragraphs, and reading fill-in-the-blanks; the listening types include multiple-choice, highlight-correct-summary, and write-from-dictation; and the integrated types such as re-tell-lecture and summarize-spoken-text combine listening with speaking or writing. The AI scoring engine evaluates the production responses on content, fluency, pronunciation, and grammatical range, so complete, natural answers outperform fragmented ones, and candidates who drill the integrated types find the score movement faster than skill-by-skill study alone.',
  'toeic-listening-and-reading.questionTypes': ' The listening section plays audio once, so the item types reward predicting the question shape while the audio runs — photograph items test present-tense descriptions, question-response items test choosing the appropriate reply, and the conversation and talk items test detail and inference from workplace exchanges. The reading types shift from grammar (incomplete sentences, text completion) to comprehension (single and multiple passages), and the multiple-passage items are the pacing challenge of the section, so candidates should rehearse the passage timing in full practice tests rather than studying the types in isolation.'
};

function expandInFile(file, section, add) {
  const p = 'src/data/examCatalog/depth/' + file + '.mjs';
  const t = readFileSync(p, 'utf8');
  const re = new RegExp("(" + section + ": \\{[\\s\\S]*?summary: ')([^']*)(')", 'm');
  const m = t.match(re);
  if (!m) { console.log('NOT FOUND: ' + file + '.' + section); return false; }
  const replaced = t.replace(re, (all, p1, p2, p3) => p1 + p2 + add + p3);
  writeFileSync(p, replaced);
  console.log('Expanded: ' + file + '.' + section);
  return true;
}

let ok = 0;
for (const [key, add] of Object.entries(fixes)) {
  const idx = key.indexOf('.');
  if (expandInFile(key.slice(0, idx), key.slice(idx + 1), add)) ok++;
}
console.log('Expanded ' + ok + '/' + Object.keys(fixes).length);
