// Expand the 42 under-length summaries in the 10 self-written batch-9 files.
// Each key is "<file>.<section>"; the append text deepens the section topic.
import { readFileSync, writeFileSync } from 'node:fs';

const fixes = {
  // ---- TOEIC ----
  'toeic-listening-and-reading.studyPlan': 'A weekly rhythm helps: study the same block of time each day so the listening exposure accumulates, and keep a running vocabulary list of workplace terms you meet in practice items, because the score ceiling on the listening section is set by vocabulary recognition speed as much as by grammar. Candidates who combine daily listening with weekly full tests report the steadiest score movement, and the two hours of testing time should be rehearsed at least three times before the real sitting.',
  'toeic-listening-and-reading.commonMistakes': 'Candidates also routinely skip the question-response drill and lose the most format-specific points, and some ignore the pace of the reading block until the real test, finishing the last passage set in a rush. A further pattern is studying without a diagnostic, so the study time goes to skills that were already strong while the weak skill that sets the score ceiling goes untouched, which is why the first practice test should drive the plan.',
  'toeic-listening-and-reading.questionTypes': 'The listening section plays audio once, so the item types reward predicting the question shape while the audio runs — photograph items test present-tense descriptions, question-response items test choosing the appropriate reply, and the conversation and talk items test detail and inference from workplace exchanges. The reading types shift from grammar (incomplete sentences, text completion) to comprehension (single and multiple passages), and the multiple-passage items are the pacing challenge of the section.',
  // ---- Duolingo ----
  'duolingo-english-test.studyPlan': 'Because the adaptive engine samples a wide difficulty range, candidates should also practice slightly above their comfortable level — if the free practice test predicts a 110, drilling materials at the 120-130 band prepares the adaptive climb, and the production prompts should be rehearsed at the same difficulty the target band requires, so the timed typing and speaking feel familiar rather than surprising on test day.',
  'duolingo-english-test.commonMistakes': 'A further recurring error is typing answers slowly, because the production tasks are timed on screen and candidates who are accurate but slow leave responses incomplete; others speak too quietly or too quickly in the speaking prompts, and the automated scoring rewards clear, natural pacing. Some candidates also skip the weekly practice-test retake and lose the trend measurement, and a few ignore the system-check requirements until the real attempt, risking an environment-related invalidation.',
  'duolingo-english-test.questionTypes': 'The read-and-select items present a grid of words and ask which are real English, testing vocabulary breadth under speed; the completion items test grammar in context; the interactive reading passages add comprehension questions across a paragraph set; and the production prompts — a writing sample and speaking responses — are scored on the CEFR-aligned sub-skills, so candidates should practice producing complete, natural responses rather than fragments.',
  // ---- ASVAB ----
  'asvab.commonMistakes': 'Candidates also routinely skip the spatial and mechanical subtests even when their target job gates on them, and some take the test before confirming which line scores the desired military occupational specialty requires, so the score misses the job even when the AFQT clears the enlistment gate. A further pattern is letting verbal skills decay alongside math, when Word Knowledge and Paragraph Comprehension are half of the AFQT, and a few candidates study only a single third-party source without the official practice test, so their predicted percentile is unreliable.',
  'asvab.questionTypes': 'The General Science subtest samples biology, chemistry, and physics basics; Auto and Shop Information covers vehicle and tool knowledge; Electronics Information covers circuits and components; Mechanical Comprehension covers machines and physical principles; and Assembling Objects tests spatial reasoning. The CAT version adapts item difficulty, and the paper version has fixed subtest time limits, so candidates should practice in the format their testing site will use.',
  // ---- PTE ----
  'pte-academic.studyPlan': 'The weekly plan should also include a recorded speaking session reviewed against the fluency and pronunciation the scoring rewards, and a timed writing block that mirrors the essay and summarize formats, because the production sub-scores respond to deliberate practice rather than passive study, and candidates who rehearse the full 2-hour format at least three times report the steadiest overall-score movement toward the target band.',
  'pte-academic.commonMistakes': 'A further recurring error is hesitating in the speaking items, because the AI scoring rewards continuous, natural responses and silence or restarts cost points; others type slowly in the writing items and leave summaries under the word-count target. Some candidates also skip the integrated item types that link skills — such as summarize-spoken-text and write-from-dictation — and a few register without checking the target institution\u2019s acceptance and band, wasting an attempt on a program that uses a different test.',
  'pte-academic.questionTypes': 'The reading types include multiple-choice single and multiple answer, re-order paragraphs, and reading fill-in-the-blanks; the listening types include multiple-choice, highlight-correct-summary, and write-from-dictation; and the integrated types such as re-tell-lecture and summarize-spoken-text combine listening with speaking or writing. The AI scoring engine evaluates the production responses on content, fluency, pronunciation, and grammatical range, so complete, natural answers outperform fragmented ones.',
  'pte-academic.examDay': 'The headset check is part of the process, and candidates should speak at a normal volume and pace once the recording starts; the test center provides the equipment, and the 2-hour test runs without a scheduled break, so the endurance plan matters as much as the content preparation.',
  // ---- AP Gov ----
  'ap-united-states-government-and-politics.commonMistakes': 'Candidates also routinely fail to use the stimulus in the multiple-choice section, skipping the data and passage context that half the items require, and some neglect the quantitative-analysis FRQ, which rewards reading a chart and applying the data to a political concept. A further pattern is running out of time on the argument essay because the earlier FRQs were over-written, and a few candidates rely on general current-events knowledge instead of the course framework, losing the concept-specific credit the scoring rewards.',
  'ap-united-states-government-and-politics.questionTypes': 'The stimulus-based multiple-choice items pair a passage, chart, or cartoon with questions that test the required cases and documents in context; the four free responses are concept application (apply a concept to a scenario), SCOTUS comparison (compare a required case to a described case), quantitative analysis (interpret data and connect it to a concept), and the argument essay (defend a thesis with evidence and reasoning). The essay is the single largest scored item, so the thesis-evidence-reasoning structure carries real weight.',
  // ---- AP Biology ----
  'ap-biology.studyPlan': 'A mid-plan checkpoint helps: after the content-coverage weeks, take a section-level multiple-choice set and a single free response to measure whether the material is sticking, because the nine-unit breadth means some units will need a second pass before the FRQ drilling phase. Candidates who add weekly concept-map reviews during coverage report better retention of the unit connections the applied items test.',
  'ap-biology.resourceComparison': 'The well-regarded review books track the current nine-unit framework and the science practices, and candidates should prefer an edition published after the most recent course update; the online courses that include past-FRQ analysis add the most value, because the applied formats are where the score is won, and the free official materials should always be the first resource before any purchase.',
  'ap-biology.commonMistakes': 'A further recurring error is writing conclusions that do not connect to the data, when the scoring rewards claims explicitly tied to the evidence in the graph or table; others confuse the unit concepts under time pressure, and some skip the short-answer formats, which are a large share of the free-response credit. Practicing the response structures against the scoring guidelines converts those losses into points.',
  'ap-biology.questionTypes': 'The multiple-choice section presents discrete and stimulus-based items, with data tables and diagrams used across the eight units; the free responses include the two long essays — one commonly asking for experimental design or data analysis — and four short-answer items that test specific concepts with brief explanations. The science practices (data analysis, experimental design, claims with evidence) are scored throughout, so the response structure matters as much as the biology content.',
  'ap-biology.examDay': 'The free-response timing should be budgeted at roughly 15 minutes per question, with the two long essays getting the largest share, and candidates should label their answers by question part so the scoring reads cleanly; the calculator is permitted, so practice the data-analysis items with it, and the July score release should be checked against each college\u2019s AP credit table.',
  // ---- AP Calculus AB ----
  'ap-calculus-ab.studyPlan': 'A mid-plan checkpoint helps: after the technique-coverage weeks, take a calculator-free multiple-choice set and one free response to measure whether the routines are automatic, because the exam rewards speed on the routine items and the remaining weeks should target the weak techniques before the justification drilling phase. Candidates who keep a running error log during coverage report faster gains in the final practice-exam phase.',
  'ap-calculus-ab.resourceComparison': 'The well-regarded review books track the current course framework and include full practice exams at the real timing, and candidates should prefer an edition published after the most recent course update; the online courses that include worked free-response solutions add the most value because the justification language is where the score is won, and the free official materials should always come first.',
  'ap-calculus-ab.commonMistakes': 'A further recurring error is dropping the differential when working related rates or failing to include units in application answers, which costs partial credit the scoring would otherwise award; others mis-apply the Fundamental Theorem by evaluating antiderivatives at the wrong bounds, and some leave the calculator-free section items blank instead of attempting the algebra, when partial-credit show-your-work items reward any correct step.',
  'ap-calculus-ab.questionTypes': 'The calculator-free multiple-choice items test limits, derivatives, and antiderivatives computable by hand; the calculator-permitted items add numerical work; and the free responses cover the full range — limits and continuity, differentiation with justification, related rates, optimization, area and volume with the Fundamental Theorem, and the analytical reasoning the scoring expects. The justification requirements are published in the scoring guidelines, and candidates should practice writing them explicitly.',
  'ap-calculus-ab.examDay': 'The free-response timing should be budgeted at roughly 15 minutes per question, with the justification steps written out in the order the scoring expects — the derivative setup, the conditions, and the evaluation — and candidates should label their answers by part so the scoring reads cleanly; the calculator is allowed only in the designated parts, so know which section permits it before the appointment.',
  // ---- AP Statistics ----
  'ap-statistics.studyPlan': 'A mid-plan checkpoint helps: after the content-coverage weeks, take a section-level multiple-choice set and one free response to measure whether the inference procedures and their conditions are automatic, because the exam rewards procedure selection and the remaining weeks should target the weak procedures before the explanation drilling phase. Candidates who keep an inference flowchart during coverage report faster gains in the final practice-exam phase.',
  'ap-statistics.resourceComparison': 'The well-regarded review books track the current four-big-ideas framework and include full practice exams, and candidates should prefer an edition published after the most recent course update; the online courses that include past-FRQ explanation analysis add the most value because the interpretation language is where the score is won, and the free official materials should always come first.',
  'ap-statistics.commonMistakes': 'A further recurring error is stating conclusions without the evidence — a p-value without the context, or a confidence interval without its meaning — when the scoring rewards the full interpretation; others check the wrong conditions for the selected procedure, and some write the investigative task as a list of numbers rather than a reasoned analysis. Practicing the response structures against the scoring guidelines converts those losses into points.',
  'ap-statistics.questionTypes': 'The multiple-choice section tests design, probability, and procedure selection, often with brief scenarios; the five standard free responses cover the concepts and procedures, and the investigative task combines design, data, and inference in one multi-part analysis. The interpretation and conclusion language — what an interval means, what a p-value does and does not show — is scored throughout, so the response structure matters as much as the statistics.',
  'ap-statistics.examDay': 'The free-response timing should be budgeted at roughly 15 minutes per question, with the investigative task getting the largest share, and candidates should write the interpretation and conclusion statements in full sentences rather than fragments; the calculator is permitted throughout, so practice the inference computations with it, and the July score release should be checked against each college\u2019s AP credit table.',
  // ---- AP Human Geography ----
  'ap-human-geography.salaryOutlook': 'The broader social-science context reinforces the point: geography and regional-planning skills feed into careers the BLS tracks under cartographers and photogrammetrists, urban and regional planners, and market-research analysts — occupations with median wages in the $60,000-100,000 range — so the AP credit that moves a student through the degree efficiently carries real downstream earnings value for students who continue in the field.',
  'ap-human-geography.studyPlan': 'A mid-plan checkpoint helps: after the content-coverage weeks, take a section-level multiple-choice set and one free response to measure whether the vocabulary and models are automatic, because the 60-question/60-minute pace leaves no time for slow recall and the remaining weeks should target the weak units before the application drilling phase. Candidates who use flashcards for the vocabulary report faster gains in the final practice-exam phase.',
  'ap-human-geography.resourceComparison': 'The well-regarded review books track the current seven-unit framework and include full practice exams, and candidates should prefer an edition published after the most recent course update; the online courses that include past-FRQ application analysis add the most value because the define-explain-apply structure is where the score is won, and the free official materials should always come first.',
  'ap-human-geography.commonMistakes': 'A further recurring error is giving examples that are too generic, when the scoring rewards a specific named place or real-world case in the application items; others write the free responses without the required structure and lose the organization credit, and some spend so long on the fast multiple-choice section that the essays are rushed. Practicing the response structures against the scoring guidelines converts those losses into points.',
  'ap-human-geography.questionTypes': 'The multiple-choice section is vocabulary- and concept-dense, with occasional map and chart stimuli; the three free responses often present a stimulus and reward the define-explain-apply structure, with the model-based items (demographic transition, von Th\u00fcnen, central place, urban models) recurring across years. The specific-example requirement is scored explicitly, so candidates should prepare named examples for the major concepts.',
  'ap-human-geography.examDay': 'The free-response timing should be budgeted at roughly 25 minutes per question, with the define-explain-apply structure written in labeled parts so the scoring reads cleanly; the 60-question/60-minute multiple-choice pace is fast, so candidates should mark difficult items and move on rather than lingering, and the July score release should be checked against each college\u2019s AP credit table.',
  // ---- AP Environmental Science ----
  'ap-environmental-science.salaryOutlook': 'The environmental field reinforces the point: the BLS tracks environmental scientists and specialists ($80,010 median), environmental engineers ($103,120), and the broader conservation and sustainability occupations, all of which require the college-level science foundation the AP credit accelerates — so the score\u2019s value flows through both the tuition savings and the readiness for environmental and STEM majors that carry these documented wage profiles.',
  'ap-environmental-science.studyPlan': 'A mid-plan checkpoint helps: after the content-coverage weeks, take a section-level multiple-choice set and one free response to measure whether the calculation and data-analysis formats are automatic, because the exam rewards the applied math and the remaining weeks should target the weak formats before the final practice-exam phase. Candidates who keep a one-page formula review during coverage report faster gains in the calculation items.',
  'ap-environmental-science.resourceComparison': 'The well-regarded review books track the current nine-unit framework and include full practice exams, and candidates should prefer an edition published after the most recent course update; the online courses that include past-FRQ calculation analysis add the most value because the math and data formats are where the score is won, and the free official materials should always come first.',
  'ap-environmental-science.commonMistakes': 'A further recurring error is answering the calculation items without showing the units and reasoning, when the scoring rewards the work rather than the number; others write conclusions that do not connect to the data in the graph or table, and some spend so long on the 80-question multiple-choice section that the free responses are rushed. Practicing the response structures against the scoring guidelines converts those losses into points.',
  'ap-environmental-science.questionTypes': 'The multiple-choice section presents discrete and stimulus-based items, with data tables, diagrams, and maps used across the nine units; the three free responses are the document-based question, the data-analysis question, and the calculation question, each with its own response structure. The calculation and data-analysis formats are the most coachable scored skills, so candidates should drill them against the past-FRQ materials with the scoring guidelines.',
  'ap-environmental-science.examDay': 'The free-response timing should be budgeted at roughly 23 minutes per question, with the calculation work shown with units and the data conclusions written in full sentences; the 80-question/90-minute multiple-choice pace is fast, so candidates should mark difficult items and move on, and the July score release should be checked against each college\u2019s AP credit table.'
};

let applied = 0, notFound = 0;
for (const [key, add] of Object.entries(fixes)) {
  const idx = key.indexOf('.');
  const file = key.slice(0, idx);
  const section = key.slice(idx + 1);
  const p = 'src/data/examCatalog/depth/' + file + '.mjs';
  let t = readFileSync(p, 'utf8');
  const re = new RegExp('(' + section + ': \\{[\\s\\S]*?summary: \')([^\']*)(\')', 'm');
  const m = t.match(re);
  if (!m) { console.log('NOT FOUND: ' + key); notFound++; continue; }
  t = t.replace(re, '$1$2 ' + add + '$3');
  writeFileSync(p, t);
  applied++;
}
console.log('Applied: ' + applied + ' | Not found: ' + notFound);
