const count = (s) => s.split(/\s+/).filter(Boolean).length;

const txCommon =
  'The most common mistakes on the Texas food protection manager certification all trace to skipping the provider course, ignoring the recall items, or misunderstanding the renewal structure: candidates who sit the closed-book exam without the course and a practice bank lose points on the fact-dense temperature and procedure items, and candidates who assume the certificate renews with continuing education are surprised that Texas requires re-certification by exam every five years. A second cluster is administrative: candidates take a non-accredited course and then discover the certificate does not satisfy DSHS, candidates fail to keep the certificate on file for the health inspector, and candidates let the five-year expiration lapse and lose the certified-manager status the establishment needs, and because most food establishments must staff a certified food manager at all operating hours, the lapse exposes the whole operation. Candidates also misread the exam details, assuming the pass bar is lower than the 75 percent most providers set, or open book when the exam is closed-book and proctored, and they underestimate the roughly 80 questions and the 90 to 120-minute clock. The recall gap is the most expensive, because the exams reward the exact holding and cooking temperatures, the four-hour danger-zone rule, date-marking, hand-washing steps, and sanitizer concentrations, and the 75 percent bar punishes guesswork. Finally, some candidates under-prepare the manager-specific content, treating the exam as a line-worker food handling quiz when the items on active managerial control, HACCP, and the person-in-charge duties carry real weight, and a few take the exam cold after only reading a summary, when the 80-question format rewards actual drilling. The mistakes are also costly: a failed attempt requires repurchasing the exam, while a candidate who invests the roughly 15-25 hours a course and practice bank require clears the bar.';

const txTypes =
  'The Texas food protection manager exams are closed-book, proctored multiple-choice tests of roughly 80 questions (plus pilot questions on some providers), with about 90 to 120 minutes allowed and a passing score typically set at 75 percent, delivered at a testing center or online with a remote proctor depending on the provider. The delivery details vary by the ANSI-accredited provider, since DSHS accepts any accredited CFP-standard exam: ServSafe runs about 80 questions plus 10 pilot questions in roughly two hours with the 75 percent bar at Pearson VUE centers or online with a remote proctor, while the Texas FoodGuard exam is 80 questions in 90 minutes at the same bar, and other accredited providers publish similar closed-book, proctored formats. The content follows the national ANSI-CFP food safety standard, with the largest weight on time and temperature control, cross-contamination and allergens, personal hygiene, and cleaning and sanitation, plus the manager-specific duties of active managerial control and HACCP, and the item style is single-best-answer with a kitchen scenario or a specific recall item in the stem. The exams are fact-dense: questions reward knowing the exact holding and cooking temperatures, the four-hour danger-zone rule, date-marking requirements, hand-washing steps, and sanitizer concentrations, rather than general reasoning about food, so candidates who complete the provider course and drill a question bank clear the 75 percent bar, while those who sit cold underperform on the temperature and date-marking items. The samples below illustrate three recurring styles: a temperature-control item, a cross-contamination item, and a cleaning and sanitation item. The sample items are editor-written illustrations of the published blueprint, not live exam items. A passing score is reported by the provider to Texas DSHS, and the certificate runs five years with re-certification by exam.';

const caTypes =
  'For candidates taking the MBLEx \u2014 the FSMTB exam that most states require and that California candidates can still take voluntarily while the CAMTC exam requirement is suspended through December 31, 2027 \u2014 the format is a 100-question multiple-choice computer-based exam in 2 hours, delivered at PSI testing centres and reported as pass/fail, with the content split across anatomy and physiology, kinesiology, pathology and contraindications, benefits and physiological effects of techniques, client assessment and treatment planning, ethics and law, and professional practice. The item style is heavily scenario-based: a client presentation or treatment situation followed by the correct assessment, technique decision, or contraindication, with single-best-answer options, so the questions reward applying knowledge to a case rather than recalling definitions. The content is not weighted evenly: anatomy and physiology and kinesiology form the largest block, with pathology and contraindications and the client-care, ethics, and law items each large, which is why the MBLEx study plan runs 80-140 hours over 8-12 weeks with anatomy up front and drilling at the end. The exam matters for portability: many California therapists still take it voluntarily, because it satisfies licensure in other states and positions the holder for portability if California reinstates the requirement after 2027 or if they move, and the FSMTB has historically reported first-attempt pass rates in the roughly 65-75 percent range. The samples below are editor-written illustrations of the published MBLEx blueprint, not live test items; for California certification itself there is currently no exam, so the question types that matter are those of the MBLEx for candidates who want the portable credential. Candidates should review the FSMTB MBLEx candidate handbook for the current blueprint, and should note that the California certification review focuses on the education transcript and the background check rather than on exam content.';

console.log('txCommon:', count(txCommon));
console.log('txTypes:', count(txTypes));
console.log('caTypes:', count(caTypes));
